### ISSUE TITLE
reviewdog_reporter: github_pr_review is not working

### ISSUE THREAD

**Issue by matthewbartos** [alaegin/Detekt-Action#26]
Hello, with this config I'm unable to see review comments with detected issues:
```
      - name: detekt
        uses: alaegin/Detekt-Action@v1.15.0.1
        with:
          github_token: ${{ secrets.PAT || secrets.TOKEN }}
          reviewdog_reporter: github-pr-review
          detekt_config: detekt-config.yml # Change config path
          reviewdog_level: error
```

Build is failing (issues detected), checks are passing, no comments are posted. The github_token is valid.
